server:
  port: 8090
  servlet:
    context-path: /springboot
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#  thymeleaf:
#    prefix: /templates/

  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 0
    timeout: 3000
